
'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True), _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)> _
Partial Public Class configuration

    Private configSectionsField As configurationConfigSections

    Private systemdiagnosticsField As configurationSystemdiagnostics

    Private applicationSettingsField As configurationApplicationSettings

    '''<remarks/>
    Public Property configSections() As configurationConfigSections
        Get
            Return Me.configSectionsField
        End Get
        Set(value As configurationConfigSections)
            Me.configSectionsField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("system.diagnostics")> _
    Public Property systemdiagnostics() As configurationSystemdiagnostics
        Get
            Return Me.systemdiagnosticsField
        End Get
        Set(value As configurationSystemdiagnostics)
            Me.systemdiagnosticsField = value
        End Set
    End Property

    '''<remarks/>
    Public Property applicationSettings() As configurationApplicationSettings
        Get
            Return Me.applicationSettingsField
        End Get
        Set(value As configurationApplicationSettings)
            Me.applicationSettingsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationConfigSections

    Private sectionGroupField As configurationConfigSectionsSectionGroup

    '''<remarks/>
    Public Property sectionGroup() As configurationConfigSectionsSectionGroup
        Get
            Return Me.sectionGroupField
        End Get
        Set(value As configurationConfigSectionsSectionGroup)
            Me.sectionGroupField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationConfigSectionsSectionGroup

    Private sectionField() As configurationConfigSectionsSectionGroupSection

    Private nameField As String

    Private typeField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("section")> _
    Public Property section() As configurationConfigSectionsSectionGroupSection()
        Get
            Return Me.sectionField
        End Get
        Set(value As configurationConfigSectionsSectionGroupSection())
            Me.sectionField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set(value As String)
            Me.nameField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set(value As String)
            Me.typeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationConfigSectionsSectionGroupSection

    Private nameField As String

    Private typeField As String

    Private requirePermissionField As Boolean

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set(value As String)
            Me.nameField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set(value As String)
            Me.typeField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property requirePermission() As Boolean
        Get
            Return Me.requirePermissionField
        End Get
        Set(value As Boolean)
            Me.requirePermissionField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationSystemdiagnostics

    Private sourcesField As configurationSystemdiagnosticsSources

    Private switchesField As configurationSystemdiagnosticsSwitches

    Private sharedListenersField As configurationSystemdiagnosticsSharedListeners

    '''<remarks/>
    Public Property sources() As configurationSystemdiagnosticsSources
        Get
            Return Me.sourcesField
        End Get
        Set(value As configurationSystemdiagnosticsSources)
            Me.sourcesField = value
        End Set
    End Property

    '''<remarks/>
    Public Property switches() As configurationSystemdiagnosticsSwitches
        Get
            Return Me.switchesField
        End Get
        Set(value As configurationSystemdiagnosticsSwitches)
            Me.switchesField = value
        End Set
    End Property

    '''<remarks/>
    Public Property sharedListeners() As configurationSystemdiagnosticsSharedListeners
        Get
            Return Me.sharedListenersField
        End Get
        Set(value As configurationSystemdiagnosticsSharedListeners)
            Me.sharedListenersField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationSystemdiagnosticsSources

    Private sourceField As configurationSystemdiagnosticsSourcesSource

    '''<remarks/>
    Public Property source() As configurationSystemdiagnosticsSourcesSource
        Get
            Return Me.sourceField
        End Get
        Set(value As configurationSystemdiagnosticsSourcesSource)
            Me.sourceField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationSystemdiagnosticsSourcesSource

    Private listenersField As configurationSystemdiagnosticsSourcesSourceListeners

    Private nameField As String

    Private switchNameField As String

    '''<remarks/>
    Public Property listeners() As configurationSystemdiagnosticsSourcesSourceListeners
        Get
            Return Me.listenersField
        End Get
        Set(value As configurationSystemdiagnosticsSourcesSourceListeners)
            Me.listenersField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set(value As String)
            Me.nameField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property switchName() As String
        Get
            Return Me.switchNameField
        End Get
        Set(value As String)
            Me.switchNameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationSystemdiagnosticsSourcesSourceListeners

    Private addField As configurationSystemdiagnosticsSourcesSourceListenersAdd

    '''<remarks/>
    Public Property add() As configurationSystemdiagnosticsSourcesSourceListenersAdd
        Get
            Return Me.addField
        End Get
        Set(value As configurationSystemdiagnosticsSourcesSourceListenersAdd)
            Me.addField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationSystemdiagnosticsSourcesSourceListenersAdd

    Private nameField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set(value As String)
            Me.nameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationSystemdiagnosticsSwitches

    Private addField As configurationSystemdiagnosticsSwitchesAdd

    '''<remarks/>
    Public Property add() As configurationSystemdiagnosticsSwitchesAdd
        Get
            Return Me.addField
        End Get
        Set(value As configurationSystemdiagnosticsSwitchesAdd)
            Me.addField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationSystemdiagnosticsSwitchesAdd

    Private nameField As String

    Private valueField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set(value As String)
            Me.nameField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property value() As String
        Get
            Return Me.valueField
        End Get
        Set(value As String)
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationSystemdiagnosticsSharedListeners

    Private addField As configurationSystemdiagnosticsSharedListenersAdd

    '''<remarks/>
    Public Property add() As configurationSystemdiagnosticsSharedListenersAdd
        Get
            Return Me.addField
        End Get
        Set(value As configurationSystemdiagnosticsSharedListenersAdd)
            Me.addField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationSystemdiagnosticsSharedListenersAdd

    Private nameField As String

    Private typeField As String

    Private initializeDataField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set(value As String)
            Me.nameField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set(value As String)
            Me.typeField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property initializeData() As String
        Get
            Return Me.initializeDataField
        End Get
        Set(value As String)
            Me.initializeDataField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationApplicationSettings

    Private excelWorkbook1MySettingsField() As configurationApplicationSettingsSetting

    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute("ExcelWorkbook1.MySettings"), _
     System.Xml.Serialization.XmlArrayItemAttribute("setting", IsNullable:=False)> _
    Public Property ExcelWorkbook1MySettings() As configurationApplicationSettingsSetting()
        Get
            Return Me.excelWorkbook1MySettingsField
        End Get
        Set(value As configurationApplicationSettingsSetting())
            Me.excelWorkbook1MySettingsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)> _
Partial Public Class configurationApplicationSettingsSetting

    Private valueField As String

    Private nameField As String

    Private serializeAsField As String

    '''<remarks/>
    Public Property value() As String
        Get
            Return Me.valueField
        End Get
        Set(value As String)
            Me.valueField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set(value As String)
            Me.nameField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property serializeAs() As String
        Get
            Return Me.serializeAsField
        End Get
        Set(value As String)
            Me.serializeAsField = value
        End Set
    End Property
End Class

