'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.34209
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.actano.de/2007/rxf", IsNullable:=false)>  _
Partial Public Class rxf
    
    Private projectproxyField() As rxfProjectproxy
    
    Private projectField() As rxfProject
    
    Private ratingField() As rxfRating
    
    Private taskproxyField() As rxfTaskproxy
    
    Private tasklinkField() As rxfTasklink
    
    Private taskField() As rxfTask
    
    Private userField() As rxfUser
    
    Private schemaVersionField As Decimal
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("projectproxy")>  _
    Public Property projectproxy() As rxfProjectproxy()
        Get
            Return Me.projectproxyField
        End Get
        Set
            Me.projectproxyField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("project")>  _
    Public Property project() As rxfProject()
        Get
            Return Me.projectField
        End Get
        Set
            Me.projectField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("rating")>  _
    Public Property rating() As rxfRating()
        Get
            Return Me.ratingField
        End Get
        Set
            Me.ratingField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("taskproxy")>  _
    Public Property taskproxy() As rxfTaskproxy()
        Get
            Return Me.taskproxyField
        End Get
        Set
            Me.taskproxyField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("tasklink")>  _
    Public Property tasklink() As rxfTasklink()
        Get
            Return Me.tasklinkField
        End Get
        Set
            Me.tasklinkField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("task")>  _
    Public Property task() As rxfTask()
        Get
            Return Me.taskField
        End Get
        Set
            Me.taskField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("user")>  _
    Public Property user() As rxfUser()
        Get
            Return Me.userField
        End Get
        Set
            Me.userField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property schemaVersion() As Decimal
        Get
            Return Me.schemaVersionField
        End Get
        Set
            Me.schemaVersionField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfProjectproxy
    
    Private idField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfProject
    
    Private versionField As Byte
    
    Private mainProjectField As Boolean
    
    Private nameField As String
    
    Private openField As Boolean
    
    Private ownerField As String
    
    Private parentField As String
    
    Private costCarrierField As String
    
    Private resourceProjectField As Boolean
    
    Private timeRecordingLevelField As String
    
    Private timeRecordingProjectField As Boolean
    
    Private uniqueHexIdentifierField As String
    
    Private idField As String
    
    '''<remarks/>
    Public Property version() As Byte
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property mainProject() As Boolean
        Get
            Return Me.mainProjectField
        End Get
        Set
            Me.mainProjectField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property open() As Boolean
        Get
            Return Me.openField
        End Get
        Set
            Me.openField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property owner() As String
        Get
            Return Me.ownerField
        End Get
        Set
            Me.ownerField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property parent() As String
        Get
            Return Me.parentField
        End Get
        Set
            Me.parentField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property costCarrier() As String
        Get
            Return Me.costCarrierField
        End Get
        Set
            Me.costCarrierField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property resourceProject() As Boolean
        Get
            Return Me.resourceProjectField
        End Get
        Set
            Me.resourceProjectField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property timeRecordingLevel() As String
        Get
            Return Me.timeRecordingLevelField
        End Get
        Set
            Me.timeRecordingLevelField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property timeRecordingProject() As Boolean
        Get
            Return Me.timeRecordingProjectField
        End Get
        Set
            Me.timeRecordingProjectField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property uniqueHexIdentifier() As String
        Get
            Return Me.uniqueHexIdentifierField
        End Get
        Set
            Me.uniqueHexIdentifierField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfRating
    
    Private modificationDateField As Date
    
    Private versionField As Byte
    
    Private activeField As Boolean
    
    Private lastAuthorField As String
    
    Private prognosisField As Object
    
    Private resultField As Object
    
    Private ratingObjectField As String
    
    Private idField As String
    
    '''<remarks/>
    Public Property modificationDate() As Date
        Get
            Return Me.modificationDateField
        End Get
        Set
            Me.modificationDateField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property version() As Byte
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property active() As Boolean
        Get
            Return Me.activeField
        End Get
        Set
            Me.activeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property lastAuthor() As String
        Get
            Return Me.lastAuthorField
        End Get
        Set
            Me.lastAuthorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property prognosis() As Object
        Get
            Return Me.prognosisField
        End Get
        Set
            Me.prognosisField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property result() As Object
        Get
            Return Me.resultField
        End Get
        Set
            Me.resultField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ratingObject() As String
        Get
            Return Me.ratingObjectField
        End Get
        Set
            Me.ratingObjectField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskproxy
    
    Private idField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTasklink
    
    Private versionField As Byte
    
    Private automaticCalculationField As Boolean
    
    Private jobLinkField As Boolean
    
    Private lagField As rxfTasklinkLag
    
    Private predecessorField As String
    
    Private secondaryLagField As rxfTasklinkSecondaryLag
    
    Private secondaryTypeField As String
    
    Private successorField As String
    
    Private typeField As String
    
    Private idField As String
    
    '''<remarks/>
    Public Property version() As Byte
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property automaticCalculation() As Boolean
        Get
            Return Me.automaticCalculationField
        End Get
        Set
            Me.automaticCalculationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property jobLink() As Boolean
        Get
            Return Me.jobLinkField
        End Get
        Set
            Me.jobLinkField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property lag() As rxfTasklinkLag
        Get
            Return Me.lagField
        End Get
        Set
            Me.lagField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property predecessor() As String
        Get
            Return Me.predecessorField
        End Get
        Set
            Me.predecessorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property secondaryLag() As rxfTasklinkSecondaryLag
        Get
            Return Me.secondaryLagField
        End Get
        Set
            Me.secondaryLagField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property secondaryType() As String
        Get
            Return Me.secondaryTypeField
        End Get
        Set
            Me.secondaryTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property successor() As String
        Get
            Return Me.successorField
        End Get
        Set
            Me.successorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTasklinkLag
    
    Private displayUnitField As String
    
    Private valueField As Short
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property displayUnit() As String
        Get
            Return Me.displayUnitField
        End Get
        Set
            Me.displayUnitField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As Short
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTasklinkSecondaryLag
    
    Private displayUnitField As String
    
    Private valueField As Byte
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property displayUnit() As String
        Get
            Return Me.displayUnitField
        End Get
        Set
            Me.displayUnitField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As Byte
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTask
    
    Private modificationDateField As Date
    
    Private positionField As UInteger
    
    Private versionField As Byte
    
    Private customvalueField() As rxfTaskCustomvalue
    
    Private actualDateField As rxfTaskActualDate
    
    Private aliasField As String
    
    Private automaticCalculationField As Boolean
    
    Private baseTaskTypeField As rxfTaskBaseTaskType
    
    Private changedField As Boolean
    
    Private defaultCalendarField As Boolean
    
    Private earliestCalculationField As Boolean
    
    Private externalField As Boolean
    
    Private finishDateFixedField As Boolean
    
    Private mainProjectField As String
    
    Private mainProjectLinkField As String
    
    Private inChargeOfField As String
    
    Private nameField As String
    
    Private notificationField As rxfTaskNotification
    
    Private noteField As String
    
    Private ownerField As String
    
    Private partnersField() As rxfTaskPartner
    
    Private parentField As String
    
    Private privateTaskField As Boolean
    
    Private subscriptionVisibleField As Boolean
    
    Private projectLinksField As String
    
    Private readAndSendLockStateField As String
    
    Private resourceTypeField As String
    
    Private remarkField As String
    
    Private rollupField As Boolean
    
    Private startDateFixedField As Boolean
    
    Private startLineField As Date
    
    Private startLineFieldSpecified As Boolean
    
    Private targetDateField As rxfTaskTargetDate
    
    Private targetDateModificationDateField As Date
    
    Private targetDateModificationDateFieldSpecified As Boolean
    
    Private taskTypeField As rxfTaskTaskType
    
    Private timeRecordingLevelField As String
    
    Private timeRecordingScheduleField As Boolean
    
    Private timeRecordingScheduleFieldSpecified As Boolean
    
    Private uniqueHexIdentifierField As String
    
    Private originalField As String
    
    Private referenceField As String
    
    Private idField As String
    
    '''<remarks/>
    Public Property modificationDate() As Date
        Get
            Return Me.modificationDateField
        End Get
        Set
            Me.modificationDateField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property position() As UInteger
        Get
            Return Me.positionField
        End Get
        Set
            Me.positionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property version() As Byte
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("customvalue")>  _
    Public Property customvalue() As rxfTaskCustomvalue()
        Get
            Return Me.customvalueField
        End Get
        Set
            Me.customvalueField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property actualDate() As rxfTaskActualDate
        Get
            Return Me.actualDateField
        End Get
        Set
            Me.actualDateField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property [alias]() As String
        Get
            Return Me.aliasField
        End Get
        Set
            Me.aliasField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property automaticCalculation() As Boolean
        Get
            Return Me.automaticCalculationField
        End Get
        Set
            Me.automaticCalculationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property baseTaskType() As rxfTaskBaseTaskType
        Get
            Return Me.baseTaskTypeField
        End Get
        Set
            Me.baseTaskTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property changed() As Boolean
        Get
            Return Me.changedField
        End Get
        Set
            Me.changedField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property defaultCalendar() As Boolean
        Get
            Return Me.defaultCalendarField
        End Get
        Set
            Me.defaultCalendarField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property earliestCalculation() As Boolean
        Get
            Return Me.earliestCalculationField
        End Get
        Set
            Me.earliestCalculationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property external() As Boolean
        Get
            Return Me.externalField
        End Get
        Set
            Me.externalField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property finishDateFixed() As Boolean
        Get
            Return Me.finishDateFixedField
        End Get
        Set
            Me.finishDateFixedField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property mainProject() As String
        Get
            Return Me.mainProjectField
        End Get
        Set
            Me.mainProjectField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property mainProjectLink() As String
        Get
            Return Me.mainProjectLinkField
        End Get
        Set
            Me.mainProjectLinkField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property inChargeOf() As String
        Get
            Return Me.inChargeOfField
        End Get
        Set
            Me.inChargeOfField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property notification() As rxfTaskNotification
        Get
            Return Me.notificationField
        End Get
        Set
            Me.notificationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property note() As String
        Get
            Return Me.noteField
        End Get
        Set
            Me.noteField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property owner() As String
        Get
            Return Me.ownerField
        End Get
        Set
            Me.ownerField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("partner", IsNullable:=false)>  _
    Public Property partners() As rxfTaskPartner()
        Get
            Return Me.partnersField
        End Get
        Set
            Me.partnersField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property parent() As String
        Get
            Return Me.parentField
        End Get
        Set
            Me.parentField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property privateTask() As Boolean
        Get
            Return Me.privateTaskField
        End Get
        Set
            Me.privateTaskField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property subscriptionVisible() As Boolean
        Get
            Return Me.subscriptionVisibleField
        End Get
        Set
            Me.subscriptionVisibleField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property projectLinks() As String
        Get
            Return Me.projectLinksField
        End Get
        Set
            Me.projectLinksField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property readAndSendLockState() As String
        Get
            Return Me.readAndSendLockStateField
        End Get
        Set
            Me.readAndSendLockStateField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property resourceType() As String
        Get
            Return Me.resourceTypeField
        End Get
        Set
            Me.resourceTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property remark() As String
        Get
            Return Me.remarkField
        End Get
        Set
            Me.remarkField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property rollup() As Boolean
        Get
            Return Me.rollupField
        End Get
        Set
            Me.rollupField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property startDateFixed() As Boolean
        Get
            Return Me.startDateFixedField
        End Get
        Set
            Me.startDateFixedField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property startLine() As Date
        Get
            Return Me.startLineField
        End Get
        Set
            Me.startLineField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property startLineSpecified() As Boolean
        Get
            Return Me.startLineFieldSpecified
        End Get
        Set
            Me.startLineFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property targetDate() As rxfTaskTargetDate
        Get
            Return Me.targetDateField
        End Get
        Set
            Me.targetDateField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property targetDateModificationDate() As Date
        Get
            Return Me.targetDateModificationDateField
        End Get
        Set
            Me.targetDateModificationDateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property targetDateModificationDateSpecified() As Boolean
        Get
            Return Me.targetDateModificationDateFieldSpecified
        End Get
        Set
            Me.targetDateModificationDateFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property taskType() As rxfTaskTaskType
        Get
            Return Me.taskTypeField
        End Get
        Set
            Me.taskTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property timeRecordingLevel() As String
        Get
            Return Me.timeRecordingLevelField
        End Get
        Set
            Me.timeRecordingLevelField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property timeRecordingSchedule() As Boolean
        Get
            Return Me.timeRecordingScheduleField
        End Get
        Set
            Me.timeRecordingScheduleField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property timeRecordingScheduleSpecified() As Boolean
        Get
            Return Me.timeRecordingScheduleFieldSpecified
        End Get
        Set
            Me.timeRecordingScheduleFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property uniqueHexIdentifier() As String
        Get
            Return Me.uniqueHexIdentifierField
        End Get
        Set
            Me.uniqueHexIdentifierField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property original() As String
        Get
            Return Me.originalField
        End Get
        Set
            Me.originalField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property reference() As String
        Get
            Return Me.referenceField
        End Get
        Set
            Me.referenceField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskCustomvalue
    
    Private nameField As String
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskActualDate
    
    Private durationField As rxfTaskActualDateDuration
    
    Private finishField As rxfTaskActualDateFinish
    
    Private startField As rxfTaskActualDateStart
    
    '''<remarks/>
    Public Property duration() As rxfTaskActualDateDuration
        Get
            Return Me.durationField
        End Get
        Set
            Me.durationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property finish() As rxfTaskActualDateFinish
        Get
            Return Me.finishField
        End Get
        Set
            Me.finishField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property start() As rxfTaskActualDateStart
        Get
            Return Me.startField
        End Get
        Set
            Me.startField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskActualDateDuration
    
    Private unitField As String
    
    Private valueField As UShort
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property unit() As String
        Get
            Return Me.unitField
        End Get
        Set
            Me.unitField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As UShort
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskActualDateFinish
    
    Private timeOfDayField As String
    
    Private valueField As Date
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property timeOfDay() As String
        Get
            Return Me.timeOfDayField
        End Get
        Set
            Me.timeOfDayField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As Date
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskActualDateStart
    
    Private timeOfDayField As String
    
    Private valueField As Date
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property timeOfDay() As String
        Get
            Return Me.timeOfDayField
        End Get
        Set
            Me.timeOfDayField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As Date
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskBaseTaskType
    
    Private typeField As String
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskNotification
    
    Private emailNotificationLevelField As String
    
    Private notifiedField As Boolean
    
    '''<remarks/>
    Public Property emailNotificationLevel() As String
        Get
            Return Me.emailNotificationLevelField
        End Get
        Set
            Me.emailNotificationLevelField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property notified() As Boolean
        Get
            Return Me.notifiedField
        End Get
        Set
            Me.notifiedField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskPartner
    
    Private personField As String
    
    Private representativeField As Boolean
    
    '''<remarks/>
    Public Property person() As String
        Get
            Return Me.personField
        End Get
        Set
            Me.personField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property representative() As Boolean
        Get
            Return Me.representativeField
        End Get
        Set
            Me.representativeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskTargetDate
    
    Private durationField As rxfTaskTargetDateDuration
    
    Private finishField As rxfTaskTargetDateFinish
    
    Private startField As rxfTaskTargetDateStart
    
    '''<remarks/>
    Public Property duration() As rxfTaskTargetDateDuration
        Get
            Return Me.durationField
        End Get
        Set
            Me.durationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property finish() As rxfTaskTargetDateFinish
        Get
            Return Me.finishField
        End Get
        Set
            Me.finishField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property start() As rxfTaskTargetDateStart
        Get
            Return Me.startField
        End Get
        Set
            Me.startField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskTargetDateDuration
    
    Private unitField As String
    
    Private valueField As UShort
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property unit() As String
        Get
            Return Me.unitField
        End Get
        Set
            Me.unitField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As UShort
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskTargetDateFinish
    
    Private timeOfDayField As String
    
    Private valueField As Date
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property timeOfDay() As String
        Get
            Return Me.timeOfDayField
        End Get
        Set
            Me.timeOfDayField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As Date
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskTargetDateStart
    
    Private timeOfDayField As String
    
    Private valueField As Date
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property timeOfDay() As String
        Get
            Return Me.timeOfDayField
        End Get
        Set
            Me.timeOfDayField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As Date
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfTaskTaskType
    
    Private typeField As String
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.actano.de/2007/rxf")>  _
Partial Public Class rxfUser
    
    Private idField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class
